### ISSUE TITLE
IL recovery for IL2Cpp Games

### ISSUE THREAD

**Issue by spiderbaldy** [AssetRipper/AssetRipper#1149]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which Unity version did this occur on?

2021.2.11f1

### Is the game Mono or IL2Cpp?

Unknown

### Describe the issue.

Whenever I put the folder into assetripper and extract it, all of the scripts have nothing in their voids.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/13806091/AssetRipper.log)

**Comment by ds5678** [comment]
From what I can see, your game ripped perfectly.

**Comment by spiderbaldy** [comment]
> From what I can see, your game ripped perfectly.

So there's nothing wrong?

**Comment by ds5678** [comment]
Your issue is being tracked here: https://github.com/SamboyCoding/Cpp2IL/issues/223

If it's any consolation, this issue is seeming more feasible lately. If my Patreon kicks off, I will likely put a substantial amount of time into contributions to Cpp2IL (because it's one of the issues my subscribers care about most).
