### ISSUE TITLE
[Bug]: Deleted my files.

### ISSUE THREAD

**Issue by Cornn-Flaeks** [AssetRipper/AssetRipper#1163]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Unselected

### Which Unity version did this occur on?

 2019.4.39.7917901

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

On Windows 10 latest Imported Risk of rain 2, left all the settings for the software at default, exported it into my download folder, then wiped everything in my downloads' folder, except the program itself. Tested it in my pictures folder too as I have nothing valuable in there, same thing wiped all other folders except ones made by Windows 10 itself. I'm using Recuva to restore my files right now, but not looking too good. Got this message:

 System.IO.IOException: Access to the path '\\?\C:\Users\demet\OneDrive\Pictures\Camera Roll' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String, Interop.Kernel32.WIN32_FIND_DATA&, Boolean) + 0x12f
   at System.IO.FileSystem.RemoveDirectory(String, Boolean) + 0xd7
   at AssetRipper.GUI.Web.GameFileLoader.Export(String) + 0x3a
   at AssetRipper.GUI.Web.Pages.Commands.Export.<AssetRipper-GUI-Web-Pages-ICommand-Start>d__0.MoveNext() + 0x11c
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xb2
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions) + 0x4b
   at AssetRipper.GUI.Web.ErrorHandlingMiddleware.<InvokeAsync>d__0.MoveNext() + 0x9f

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/13952733/AssetRipper.log)

**Comment by SSM0770** [comment]
This isn't a bug, this is how it's intended to work.

The program expects you to dump the extracted contents into an empty folder so the export is clean and doesn't conflict with other potential exports, and it will clear the directory to make sure of that. There used to be a warning displayed about this before it moved to web UI, but it hasn't been reimplemented yet.

**Comment by ColorBuffer** [comment]
It's not a bug it's a joke here is the code:

on success: put the content in a new folder in destination 

on error: remove content, destination and its parent :)

**Comment by SSM0770** [comment]
> It's not a bug it's a joke here is the code:
> 
> on success: put the content in a new folder in destination
> 
> on error: remove content, destination and its parent :)

The very **first** thing the program does upon confirming export is to clear the destination folder regardless it it’s successful in the end or not, that way if there’s another ExportedProject folder in the destination, it doesn’t export to the preexisting folder.

It does not “put the content in a new folder,” it puts the content _directly_ into the destination **after** clearing the destination. The destination you pick needs to already be a new folder, not one with stuff already in it.

As I mentioned above, the program used to warn of this before it moved to Web UI, but since Web UI is essentially starting from scratch, it disappeared and hasn’t returned yet.

**Comment by DreadKyller** [comment]
Frankly that's unacceptable behavior from the code. You should **never** just delete files without notice. If you need to clear a folder to make sure it's empty for export, and there are files currently present, **warn** the user that continuing will delete the files and have them be able to back out of the operation, a popup saying "The folder you selected contains files. All files in the destination will be deleted, continue?". This is how almost all exporting software works, users shouldn't be expected to expect the program will delete content, especially without warning. It's common with other software that generates or exports files to append files to the current list of files, and users without warning have no reason to believe this software works differently. It's common for people to export directly to Desktop for example, deleting files without warning could completely ruin people's computers.

**Comment by ds5678** [comment]
It is not trivial. If you think it is, make a pull request.

**Comment by DreadKyller** [comment]
> I

Might just do so. As for "not trivial", excuse me, it's a check for whether the directory contains files, if true show a popup where clicking yes goes executes the export, otherwise go directly to the export. These operations are frankly fundamental.

**Comment by ds5678** [comment]
> show a popup

This is the obstacle.

**Comment by TheGameratorT** [comment]
This is just pure ignorance, who the hell thought this was a good idea?

**Comment by ds5678** [comment]
> who the hell thought this was a good idea?

As benevolent dictator for life, I the hell thought this was a good idea.

> This is just pure ignorance

Presumptuous. I anticipated this outcome and forged ahead. Only a small portion of users encounter the problem; the remainder learn to use the software before anything bad happens.

At the time of the decision, I had higher priorities. With the release of AssetRipper Premium, this and any similar issues are receiving heightened development attention. Users who pay deserve a safety net against unfortunate outcomes, and there's no reason not to make the changes also available to free users.

> Not even with a warning should this ever be the default behavior. Have it create a sub-directory on the directory you are exporting to.

Your opinion will be taken into consideration.

**Comment by ZoruaLoL** [comment]
Got the same issue, can't believe this is supposed to be an "upgrade" from the previous version (don't get why it needs to run from my browser instead of having its own GUI) which _didn't_ have this issue. 
It's fucking common sense.

**Comment by ds5678** [comment]
You guys are welcome to submit pull requests. If you're not subscribed to Patreon, you have no entitlement over my time.

**Comment by TheGameratorT** [comment]
I don't think anyone is going to make a pull request to a tool that is now going into the opposite direction and weirdly enough focusing on transitioning to a web UI. At most one would do it just to protect new users that could come across the same fate, because if this happens in the free version I bet the paid version is no less different. I'll just stick with the older versions.

**Comment by ds5678** [comment]
> I'll just stick with the older versions.

I don't understand this mentality. This issue is entirely avoidable by the user, with almost no effort. Why would you forego the improvements of newer versions?

**Comment by TheGameratorT** [comment]
> I don't understand this mentality. This issue is entirely avoidable by the user, with almost no effort.

That is true, but I prefer the old UI anyway. I don't get why this needs a browser interface that will call the file dialog through the program anyway, it's not like I want to have the program running on a server to access remotely.

> You guys are welcome to submit pull requests. If you're not subscribed to Patreon, you have no entitlement over my time.

You could probably do this change in just about some minutes, someone else would need to spend most of the time learning the code base instead of just making the fix which would could take hours.
But instead you prefer to act the victim and expect someone else to spend unpaid time for the tool in which you are going to be the one profiting from.

> the remainder learn to use the software before anything bad happens

This is complete nonsense because nowhere there is an indication on how the export option should be used and if there is, it isn't obvious. If that is the case, then the only option would be for the average user to just be told by someone else or to spend a bunch of time learning someone else's source code to make sure how the program should be used.

I anticipated this behavior and proceeded anyway just because it wasn't much of an important folder for me, it was just the Lethal Company installation folder.

It's not mostly for me that I worry but mostly for others that are less experienced and are not aware that such tools could have fatal flaws like these. It makes perfect sense for a user to select any folder and expect it to not be deleted.
Initially I expected a "ExportedProject" folder to be created in the output directory, that if I am not mistaken is how older versions did it. (I might be mistaken for another tool or maybe I made the folder myself, but I doubt it)

And while I do respect that the tool is yours and you choose what to do with your time, this is more than a just a flaw or a feature request. It is an harmful flaw, comparable to malware.

**Comment by ds5678** [comment]
> I don't get why this needs a browser interface

I did not like Avalonia.

> You could probably do this change in just about some minutes

I am not in the habit of ignoring trivial fixes. If I could have fixed this trivially, I would have already done so.

> expect someone else to spend unpaid time

I don't. I was simply pointing out the nature of open-source work: that everyone's time is their own and that it's disrespectful to expect unpaid time from anyone.

> It is an harmful flaw

True. I am unsatisfied with AssetRipper's current state and am actively working to remove weaknesses such as this one.
