### ISSUE TITLE
[Enhancement]: WebPlayer Game Paths

### ISSUE THREAD

**Issue by ds5678** [AssetRipper/AssetRipper#120]
### Describe the new feature or enhancement

Currently, AssetRipper cannot detect assemblies in WebPlayer games due to a lack of knowledge about their placement in the game file structure. As a result no scripts can be exported when ripping these games. The relevant class is named `WebPlayerGameStructure`.

**Comment by m00nligh7** [comment]
That will be good, if this feature will appear soon. In example, i really want to extract all old Unity WebPlayer games and export them to new platforms(because i want to play them again, i have untiy3d files)(only for my personal use or for web archiving them :shrug:). I will wait for this feature, hope, you will make this U.U. I want to help, but i dont know the game file structure at this time.
