### ISSUE TITLE
[Question]: Why have a `premium` version when the project is open source? just let the community help with the most latest versions

### ISSUE THREAD

**Issue by AMaskedDev** [AssetRipper/AssetRipper#1307]
### Question

I'm no expert, I some experience in c# and I'd like to help just the most latest versions I may be no help at all but I'd like to support this project by helping out in some way or another. Thanks :>

### Are you sure you want to clutter the issues section?

Yes, I acknowledge that my question may be ignored because I am not following directions.

**Comment by ds5678** [comment]
Having a premium edition allows me to reward generous users with additional features that I might not have had time to implement otherwise.

It also helps to sustain the overall project by giving me a financial incentive to continue maintaining core parts like supporting new Unity version updates. I've seen so many similar projects become abandoned. I don't want that to happen to AssetRipper.

**Comment by Eloren1** [comment]
What is a premium version anyway? There is no information about it at all. @ds5678

**Comment by ds5678** [comment]
Patreon subscribers get access to additional features.

**Comment by Eloren1** [comment]
What are the features? I asked about that version, but you still haven't explained lol.

**Comment by ds5678** [comment]
https://www.patreon.com/posts/premium-launch-97523831
