### ISSUE TITLE
[Bug]: High RAM Usage Compared to 6 months ago

### ISSUE THREAD

**Issue by MARK2580** [AssetRipper/AssetRipper#1409]
### Are you on the latest version of AssetRipper?

No, I need to download a newer version and try again.

### Which release are you using?

1,0.18

### Which game did this occur on?

Rise of Eros

### Which Unity version did this occur on?

I don't know

### Is the game Mono or IL2Cpp?

Unknown

### Describe the issue.

What happened to the program over the past six months, why does it now work through a browser. I can’t unpack a single game because all 32 gigabytes of RAM and another 32 gigabytes of the swap file simply evaporate in a few minutes and Windows begins to close all open programs, even removing the desktop background. WHY was this done, the previous version had its own personal interface, for some reason the later ones became an installer that didn’t even ask where to install the program.

### Relevant log output

![scr_10_07_2024_11_04_51](https://github.com/AssetRipper/AssetRipper/assets/11617079/4f8e2e8e-fed0-49b7-ae80-15c03e91c2d2)

**Comment by ds5678** [comment]
My understanding of your words is that your primary concern is in regards to RAM usage. You perceived an increase in the amount of RAM required, compared to AssetRipper versions released six months ago. Is that correct?

I have ideas about how this might have happened, and I can do performance analysis to verify my suspicions. Although AssetRipper will likely always be greedy about memory usage, we can hopefully reduce its footprint to a more manageable level.

**Comment by OpenA** [comment]
I think the author just tried using the web interface for some reason (maybe he likes VS Code or 360 Office)
 But he tryed to do that without using node and js+css+html just with Net
 As a result we have website from 2000x running on localhost

address to the autor(s): you pass by a wrong way, first - you template-generated pages loads  js/css from the internet domains.
Secondly, the content on websites is more static than in desktop applications, and browsers are designed to cache everything that has previously been visited, including scripts and styles.
The modern approach of the web ui is a using skeletion html with a bunch of scripts,  all what is created on the page with js is not cached (excluded js requests of couse).

In any case, a page with hyperlinks + external js/css is not an app ui. Try something else, or ditch .net in the UI and make normal electron or qt/qml app.

**Comment by OpenA** [comment]
~~Try something else, or ditch .net in the UI and make normal electron or qt/qml app.~~

Or maybe just create a static files in the app folder (like in nwjs framework):
*  www/index.html
*    www/settings.html
*    www/js
*    www/css

run the mono/Net server from this (www) folder and give user permissions for all files. do not use external domain js/css/image resources and do not disabling browser securities like a CORS.
Instead of tamplate generations use the get/post request or websocet ports for send commands and visual informations betwin client scripts and net/mono server for update content dinamicly? without reloading/parsing document for any user actions.
Maybe better just put url adress in console (like python http.server does for example) without opening a browser.
finally can be making package.json and running same folder with external nwjs/electron like an alternetive.

**Comment by ds5678** [comment]
@OpenA do you have any evidence that the web UI is causing higher ram usage?

**Comment by OpenA** [comment]
> do you have any evidence that the web UI is causing higher ram usage?

I don't say anything about ram usage. Obviously this is a i2cpp problem, maybe because this technology createt for the apps with static resources (like a games) and not suitable for open/close load/reload design software, because c++ has no any garbage collector. This is a strictly my opinion of couse.

**Comment by ds5678** [comment]
I discovered that the high memory usage is, in part, due to infrequent garbage collection. If I manually trigger the garbage collector after each asset export, the improvement is significant. Maximum ram usage for my tested game decreased by about 1/5, and average ram usage appears to have decreased by half. Of course, this comes at the cost of a speed penalty; the export took approximately 50% longer.

Given the speed penalty, spamming the garbage collector is not an ideal solution. Further investigation will likely uncover more efficient places to trigger garbage collection.

The memory profile also gave insights into what object types were holding the most memory. In my case, `YamlScalarNode` was by far the largest memory user, which gives new importance to #1381. Eliminating some of the allocations for byte array scalars may significantly reduce memory usage and improve performance.

**Comment by ds5678** [comment]
I re-profiled on the same game, and maximum ram usage appears to have reduced by 2/3. Ram usage during export is relatively stable. There are no longer any large spikes. I appreciate you and others bringing this to my attention.
