### ISSUE TITLE
[Enhancement]: Save Shaders. I literally cannot view scenes for the life of me because all the materials use shaders

### ISSUE THREAD

**Issue by EthanJamesBarron** [AssetRipper/AssetRipper#242]
### Describe the new feature or enhancement

Is it possible to save the code inside a shader when decompiling? I want to view levels but because the materials all use a Vinyl shader I can't. Any help?

**Comment by ds5678** [comment]
Shaders are notoriously difficult to decompile, for numerous reasons that I will not go into here.

What you have now is better than uTiny produced, which made everything pink because the shaders would never compile. AssetRipper produces dummy shaders in order to guarantee compilable output that takes the same parameters as the original shader.

Someday, AssetRipper _might_ have full shader decompilation, but that is a mammoth task, so don't expect anything.

**Comment by EthanJamesBarron** [comment]
> Shaders are notoriously difficult to decompile, for numerous reasons that I will not go into here.
> 
> What you have now is better than uTiny produced, which made everything pink because the shaders would never compile. AssetRipper produces dummy shaders in order to guarantee compilable output that takes the same parameters as the original shader.
> 
> Someday, AssetRipper _might_ have full shader decompilation, but that is a mammoth task, so don't expect anything.

Dang I didn't know it was that hard. Sorry lol
