### ISSUE TITLE
[Enhancement]: Use MuscleClipConstant for Animation Recovery

### ISSUE THREAD

**Issue by MrGrizzzzly** [AssetRipper/AssetRipper#251]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

4.2.2.78157

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Update 1.9.0 fixed #22, but now there is the same problem as in uTinyRipper: almost all animations are not exported(empty files are exported that weigh 1-2kb) 
https://drive.google.com/file/d/187wRY4QCM2_eXR3f3alTMmxpc0Qnc_zk/view?usp=sharing

**Comment by ds5678** [comment]
Hi, I was able to verify your experience. This is happening because the vast majority of your animation data has been compiled into the `ClipMuscleConstant` class. This class is "release-only" which means it can't be serialized to unity yaml assets for use in the Editor. It must be converted into other animation assets in order to be usable.

In other words, this isn't a bug, it's just not a feature. You are welcome to work on it. I have resources available to help you. There are versioned assemblies on the [AssemblyDumper](https://github.com/AssetRipper/AssemblyDumper/tree/v_development) repository. Each one contains lots of information about the structure of Unity assets. The assemblies can be decompiled with [ILSpy](https://github.com/icsharpcode/ILSpy).

**Comment by MrGrizzzzly** [comment]
I don't quite understand what decompilation of assemblies will give me, I'm not a programmer.

**Comment by ds5678** [comment]
If you're not a programmer (or willing to become one), then the assemblies won't help you.

However, you should be aware that unless people come out en masse requesting this feature, I will likely never work on it. I have other priorities, many of which will impact large sections of the userbase.

**Comment by ds5678** [comment]
Closed because of inactivity
