### ISSUE TITLE
[Bug]: Unable to read MonoBehaviour, because script layout KeyFrameManager mismatch binary content

### ISSUE THREAD

**Issue by skyline9394** [AssetRipper/AssetRipper#260]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest alpha-build of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

![Capture111](https://user-images.githubusercontent.com/23480817/152805858-10c069ef-6961-4b90-9f6c-66e80b427583.PNG)

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

![Capture111](https://user-images.githubusercontent.com/23480817/152806399-a6ff26df-542f-44b1-8f72-cc5776a51aba.PNG)

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/8015977/AssetRipper.log)

**Comment by skyline9394** [comment]
understand so what i can do to get more info for you to fix it or what programs can i use to get more info about the tree

**Comment by QuinnBast** [comment]
I'm also running into this issue.

I think what is happening is that the asset ripper is not importing any DLLs in the project files before it attempts to export scripts. In my case, the `AudioVoice` class is defined in one of the dlls in the `Managed` folder, however, the ripper attempts to export the MonoBehaviour and map it to a class before it imports the DLL in the logs...

> Import [Warning] : Unable to read MonoBehaviour, because valid definition for script EventTrigger wasn't found
Import [Warning] : Unable to read MonoBehaviour, because valid definition for script GroupComponentProxy wasn't found
Import [Warning] : Unable to read MonoBehaviour, because valid definition for script GroupComponent wasn't found
Import [Warning] : Unable to read MonoBehaviour, because valid definition for script EventListener wasn't found
...


Actually a more in depth look at the logs shows that AssetRipper doesn't attempt to import any dlls other than Assembly-CSharp.dll

**Comment by ds5678** [comment]
@QuinnBast Your monobehaviour read issues are different from skyline's. On their game, everything was found; it just didn't match what was in the game files.

Assuming there was a regression in AssetRipper for importing dll's, can you find the version at which it occurred?

**Comment by ds5678** [comment]
Closed because duplicate of #229 and inactivity
