### ISSUE TITLE
[Bug]: $ sings in game made before 2013 

### ISSUE THREAD

**Issue by BurAndBY** [AssetRipper/AssetRipper#264]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

Unknown, no globalgamemanager

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

[Games made before 2013](https://m.apkpure.com/portalize/com.heaval.portalize) give $ sign randomly

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/8041736/AssetRipper.log)

**Comment by ds5678** [comment]
So what exactly is the problem?

**Comment by ds5678** [comment]
Those $ signs aren't random. They're compiler generated for the creation of an enumerator. Although it's possible that Unity compiled enumerators their own way, this is likely a "bug" in ILSpy. Since AssetRipper isn't involved with the minutiae of decompiling scripts, this cannot be considered a bug for AssetRipper.
