### ISSUE TITLE
[Bug]: ComputeShader read errors on 2020.3.10f1

### ISSUE THREAD

**Issue by NWPlayer123** [AssetRipper/AssetRipper#309]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2020.3.10.32120 (2020.3.10f1)

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

I tried to import [Have a Nice Death](https://steamdb.info/app/1740720/) and it spit out a lot of errors trying to read the UnityFS and asset bundles for the game. It looks like it's reading strings and expecting it to be the size parameter (1953656659 -> "troS")

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/8241280/AssetRipper.log)

**Comment by ds5678** [comment]
I'll take a look in a second. I expect it'll be an easy fix

**Comment by ds5678** [comment]
I fixed Sprites in 75393b91c452585529a34f816b65c72394b192dc, but compute shaders require more attention than I'm willing to give at this moment since #164 is nearing completion.

If you would like to fix this and submit a pull request, here is a diff for compute shaders:
[ComputeShaderDiff.zip](https://github.com/AssetRipper/AssetRipper/files/8241523/ComputeShaderDiff.zip)

**Comment by NWPlayer123** [comment]
I'll probably wait for 164/0.2.0.0 then, thanks for giving it a look
