### ISSUE TITLE
[Enhancement]: Use Yaml Audio Exporter

### ISSUE THREAD

**Issue by githubexplorer2342** [AssetRipper/AssetRipper#411]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

https://steamdb.info/app/1707550/

### Which Unity version did this occur on?

2020.1.4f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

After exporting the game, i noticed that all audio files that are with .wav dont play at all, while the ogg files play fine. And plus, some of the wav files have the same name like the ogg files.

For example: one file is named 1.ogg, while the other duplicate is named 1.wav.
I have tested on AssetStudioGUI to see if the .wav files worked, and turns out it worked fine.

**Comment by ds5678** [comment]
The comparison to AssetStudio is unwarranted because it converts everything to wav. Where possible, AssetRipper retains the audio format (usually ogg) to prevent conversion from a lossy format to a lossless format.

In regards to the AssetRipper "wav" files that don't play, I suspect it's the same situation as Font. Most font assets contain no font data and must be exported as yaml. I have a yaml audio exporter, but it doesn't currently get used. Whenever I remove FMOD, I'll revamp the audio export hierarchy.

**Comment by githubexplorer2342** [comment]
Oh, i understand now. Thanks for the information.

**Comment by githubexplorer2342** [comment]
I inspected the .wav files closer and i realized they are playable, but its just 0 seconds of nothingness.

**Comment by githubexplorer2342** [comment]
Hello, ds5678! Little update on the issue: the wav files still dont work on the default, convert to wav or convert to mp3 options. And i think i know why.
Looking on the audioclip compression format, the wav files use ADPCM compression, which i think assetripper dosent support.

**Comment by ds5678** [comment]
> Should i make a seperate issue about this?

Yes, on SamboyCoding/Fmod5Sharp
