### ISSUE TITLE
[Bug]: Dummy class. Use different settings or provide .NET dll files for better decompilation output

### ISSUE THREAD

**Issue by tuanvus** [AssetRipper/AssetRipper#483]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

https://play.google.com/store/apps/details?id=com.N4KGames.TapTapCube

### Which Unity version did this occur on?

unity 2020.2.2

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

I tried installing in the interface but still can't translate the code to dc

**Comment by ds5678** [comment]
Please upload your full log

**Comment by tuanvus** [comment]
![image](https://user-images.githubusercontent.com/87792686/182294643-93cc1ee9-eca7-4712-b0e7-7802cdbc72b7.png)
I have a problem in some games that won't be reposding in this case, but it just hangs like this and won't run anything.
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/9239128/AssetRipper.log)

**Comment by ds5678** [comment]
> still can't translate the code to dc

What is `dc`?

> it just hangs like this and won't run anything

Cpp2IL's attribute recovery is very slow for android games. Attributes are required for correct `MonoBehaviour` deserialization. I consulted with the community, and they decided that running slow is better than breaking deserialization.

> Dummy class. Use different settings or provide .NET dll files for better decompilation output

I assume you got this when you set scripts to level 0, which is expected behavior.

**Comment by tuanvus** [comment]
I would consider , but bug Use different settings or provide .NET dll files for better decompilation output ,
why this error, i tried setting the levels from 0->4 and still got

**Comment by ds5678** [comment]
> but bug Use different settings or provide .NET dll files for better decompilation output 

This is not a bug. I implemented #427 to improve export quality. Previously, it would export nothing and your `MonoBehaviour` assets would have missing scripts.

> why this error, i tried setting the levels from 0->4 and still got

* Script content level 0: Empty scripts are normal and expected behavior because IL2Cpp information is being explicitly ignored.
* Script content levels 1 - 4: AssetRipper runs slow because Cpp2IL is inefficient on Android games. This is currently outside my control.
