### ISSUE TITLE
[Enhancement]: Static Mesh Separation

### ISSUE THREAD

**Issue by Wolfskii** [AssetRipper/AssetRipper#498]
### Describe the new feature or enhancement

As of now often meshes tend to start as combined after the ripper process often leading to issues like not being able to move, rotate or transform them in the project. Is there a possibility for a feature to separate the meshes?

**Comment by walllable** [comment]
You can try the .glb exporter in the most recent alpha build - That let me separate the sub-meshes in my model, which had pretty much everything marked as static in the original version.

**Comment by Wolfskii** [comment]
> You can try the .glb exporter in the most recent alpha build - That let me separate the sub-meshes in my model, which had pretty much everything marked as static in the original version.

Do you mean the Simple GLB under Mesh Export Format in v0.2.2.0?
It says that unity cannot import that type of asset, so I assume I will lose all references? :)

**Comment by ds5678** [comment]
The GLB mesh exporter that @walllable mentioned is available in the alpha builds, but not yet in a release. The improvements I've made separate all the submeshes during export. 

I've also been working on a GLB model exporter, which exports a scene / prefab as a GLB file. This format includes the full node structure including names. It is not yet pushed to GitHub.

However, I don't think GLB is what you want. You want the mesh to stay referenced in Unity, so that makes GLB untenable in your use case. You need the separated meshes to be in native unity yaml format. 

This is a complicated request, but I do have plans for it at some point. Essentially, this can be divided into a couple parts:

1. Identify static meshes and extract their data into normal C# data types.
2. Use mesh data and game object names to create identifiable separated mesh data.
3. Remove duplicate mesh data.
4. Pack the unique mesh data into new Unity meshes.
5. Add the meshes to a virtual file.
6. Change renderer references to the virtual meshes.

* 1 and 2 are easy and already being done for my GLB model exporter. 
* 3 is hard because of rounding errors and the requirement for scale invariance. 
* 4 is intermediate. I have a good understanding of the meshes, so it shouldn't be too bad.
* 5 and 6 require improvements to AssetRipper's design in order to be done right.

**Comment by Wolfskii** [comment]
> The GLB mesh exporter that @walllable mentioned is available in the alpha builds, but not yet in a release. The improvements I've made separate all the submeshes during export.
> 
> I've also been working on a GLB model exporter, which exports a scene / prefab as a GLB file. This format includes the full node structure including names. It is not yet pushed to GitHub.
> 
> However, I don't think GLB is what you want. You want the mesh to stay referenced in Unity, so that makes GLB untenable in your use case. You need the separated meshes to be in native unity yaml format.
> 
> This is a complicated request, but I do have plans for it at some point. Essentially, this can be divided into a couple parts:
> 
> 1. Identify static meshes and extract their data into normal C# data types.
> 2. Use mesh data and game object names to create identifiable separated mesh data.
> 3. Remove duplicate mesh data.
> 4. Pack the unique mesh data into new Unity meshes.
> 5. Add the meshes to a virtual file.
> 6. Change renderer references to the virtual meshes.
> 
> * 1 and 2 are easy and already being done for my GLB model exporter.
> * 3 is hard because of rounding errors and the requirement for scale invariance.
> * 4 is intermediate. I have a good understanding of the meshes, so it shouldn't be too bad.
> * 5 and 6 require improvements to AssetRipper's design in order to be done right.

Ah I see.
That would be amazing once that makes a release. Most ripped scenes I have recently have these static combined meshes that I can't do anything with in the scene, making it impossible to edit or reuse from there. I do understand it's something that might be a bit difficult and take time until it hits. Was more curious if that even was something that was in the plans.

I guess for now I could try to use the exported GLB-files and add them manually to Unity once that makes the releases.

**Comment by ds5678** [comment]
Although there are still some kinks to work out, this has been more-or-less implemented.
