### ISSUE TITLE
[Enhancement]: Ability to select two types of unity object such as AnimationClip and Mesh, to export. And a toggle button which disables clearing of files

### ISSUE THREAD

**Issue by realtrollman2319** [AssetRipper/AssetRipper#570]
### Describe the new feature or enhancement

Holding CTRL then selecting two unity type files, then export selected file would be nice.
And a button which disables deletion of existing folders on exporr path.

**Comment by ds5678** [comment]
> Holding CTRL to select multiple Unity types

Not likely to be implemented in this Graphical User Interface, but maybe the next one.

> Disable deletion of existing files and folders in export directory.

Not likely to ever happen.

**Comment by realtrollman2319** [comment]
How about toggle instead of delete?

**Comment by ds5678** [comment]
> How about toggle instead of delete?

No. I am against this for several reasons:
* I feel that it would create misconceptions about how AssetRipper functions. For example, exporting files separately and merging later does not result in a complete project. It breaks any references between the separated parts. Users might think otherwise if I allowed this.
* It makes debugging more difficult when users report bugs.
