### ISSUE TITLE
[Bug]: Title is underlapping with window control buttons on macOS

### ISSUE THREAD

**Issue by valentinegb** [AssetRipper/AssetRipper#682]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

MacOS Arm64

### Describe the issue.

The window title is underlapping with the window control buttons on macOS.

![Screenshot 2023-01-10 at 2 26 40 PM](https://user-images.githubusercontent.com/35977727/211675541-41cb5c77-3d81-4341-b0ff-b54445d14559.png)

**Comment by ds5678** [comment]
Well, that's annoying

**Comment by ds5678** [comment]
I see a couple feasible solutions:

* Go back to having the control buttons in their own section of the UI.
* Move the AssetRipper text to the middle of the header.
* Move the AssetRipper text right by x pixels.
* Insert an unimportant image to the left of the AssetRipper text.

I do not like any of these options. Ideally:

* OSX buttons could be moved to the right side of the window using code in AssetRipper. (Doubtful)
* A different header is used on each of the major platforms.
  * This would also solve the issue on Linux where a header is unnecessary since the default header doesn't get merged like Mac and Windows.

Is this something you want to work on?

**Comment by valentinegb** [comment]
The title could be removed for Mac really, since it's not common for apps to show the app name in the window on that platform. This is usually okay because the name of the app is shown in the menu bar, however this currently isn't the case (it shows "Avalonia Application").

Unfortunately I don't know C# or probably any of this project's tech stack, I'm just a user. Sorry!

**Comment by valentinegb** [comment]
I made a little mockup with SwiftUI, hopefully this can serve as a reference for how it should look on Mac (at least, for the toolbar and menu bar, you don't really need to worry about the rest).

https://user-images.githubusercontent.com/35977727/211717978-a0d83a04-5eeb-4729-9b6a-f157059b9cf6.mp4

**Comment by ds5678** [comment]
Thank you!

FYI I have never owned a Mac, so I'll need you to test when the time comes.
