### ISSUE TITLE
[Bug]: Incorrect UVs in Separated Static Meshes

### ISSUE THREAD

**Issue by Zbuffers** [AssetRipper/AssetRipper#683]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Tested on 3 games 
using version 0.3.0.4 released
and latest commit as of 9/01/2023

### Which Unity version did this occur on?

2019.3.11
2020.3.29f1
2020.3.35f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Hi, 
When using Static Mesh Seperation, I noticed that the seperated meshes have incorect UVs.
I noticed this because these meshes have a textured material that does not show.
When I export without the Static Mesh Seperation, the UVs are correct (in the corresponding Combined Mesh (root_ scene) xxx.asset

I can provide example exported mesh assets with incorrect UVs if you want to check this.

Also, just a question, What does 'enable Prefab outlining' do ?

Anyway,
Keep up the great work ;)
Regards,
Zbuffer

### Relevant log output

n/a no relevant info in the log.
I can provide one if needed.

**Comment by ds5678** [comment]
Hi Zbuffer, nice to hear from you again. 

> Incorrect UVs for splitted static meshes

Although I was not aware of this, I am not surprised. Static Mesh Separation has been a crapshoot since it was implemented.

> Also, just a question, What does 'enable Prefab outlining' do ?

It creates new prefabs from scene hierarchies. Although it is also an experimental feature, it's far more stable than static mesh separation.

**Comment by Zbuffers** [comment]
Hello, just a small bump ;) ...

Has any one else noticed this ?
Is there anyone trying to fix this ?
I think this is kind of high priority, since it make the static mesh separation quite useless without UVs...
All attemps (10+ projects from various unity versions) have failed (for me)...
looking forward for any answers/fixes

Kind regards
Z

**Comment by ds5678** [comment]
Hi Z,

It's nice to hear from you. I hope things are going well.

Project development has been mostly me lately, so progress normally happens in whatever direction I feel like working. In the case of this, the feature is still experimental, so I don't feel much urgency to fix any bugs, especially since I have so much going on right now.

Are you in the discord server? We've been talking about some of the big potential improvements lately. Given your interest and experience, it might be nice to hear your opinions.

Jeremy

**Comment by ds5678** [comment]
This is embarrassing. I think I solved the problem, and it was really stupid.

**Comment by Zbuffers** [comment]
Wow !!!
This My TOP N1 issue !!!
Thanks so much for looking into this ;) ;) ;)

I'm downloading and testing ASAP !!!

**Comment by ds5678** [comment]
You're welcome, though I can't take all the credit. @tongguang was the one who found it.

**Comment by ds5678** [comment]
How did your testing go?

**Comment by Zbuffers** [comment]
Hi,
Haven't had time to test it yet...
Currently on the road to my summer place... ;)

Using latest version of Pummel party game to test ... ;)
It has changed a lot since last version (mostly using bundles with adressables, now)

I have extracted the project fine.
Will need a little time to put the project in shape for Unity Import.
But I think I should be able to report tomorow.

Note: I saw the change you made in the commit ;) lol ;) pfff ;)
Better this than a big rework ;)

For me it's BIG thing ! at last we have static meshes separated !!!

Very king regards ;)
Z

**Comment by ds5678** [comment]
How did it go?

**Comment by Zbuffers** [comment]
Sorry for the (very) late reply. I faced various familly and PC issues... all resolved now.
I think this nailed it.
all Uvs are correct (UV0 and UV2) and static flags are set.
Congrats. !!!

**Comment by ds5678** [comment]
Glad everything worked out!
