### ISSUE TITLE
[Bug]: Animator Controllers are empty and things won’t load

### ISSUE THREAD

**Issue by 1036023** [AssetRipper/AssetRipper#684]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

DuckWorld: Smart Adventures
Installer can be found here: [https://archive.org/details/DuckWorld-1.3.2](url)

### Which Unity version did this occur on?

Unity 5.2.2p1 and 2021.3.16f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

When I load the game in 5.2.2p1 all the levels look fine, just untextured, but the animator controllers are completely empty. When I upgrade the game to Unity  2021.3.16f1 all the textures are applied, the animator controllers work but some of the levels miss almost everything.
How can I get best of both worlds?
![Schermafbeelding 2023-01-13 142141](https://user-images.githubusercontent.com/120372357/212330804-703937f3-6de7-4d5c-a739-c80332d5139c.png)
![0E318C8D-A9D5-44CB-A602-3AEE10FB2B18](https://user-images.githubusercontent.com/120372357/212330959-a91661fe-052c-49a7-b4f8-a70332366de6.png)

**Comment by ds5678** [comment]
Okay, first of all, making that large of a version bump is problematic even for normal Unity projects. I make no guarantees about the result.

> Levels miss almost everything

This is likely because you bumped over 5.5, which breaks static meshes.

> Animator controllers in unity 5 are empty but not unity 2021

For them to work in 2021, they can't be empty in unity 5. If they were empty in unity 5, they would still be empty in unity 2021.
