### ISSUE TITLE
UI Rewrite

### ISSUE THREAD

**Issue by ds5678** [AssetRipper/AssetRipper#919]
## Context

AssetRipper is planning to replace [Avalonia](https://github.com/AvaloniaUI/Avalonia) with [Electron.NET](https://github.com/ElectronNET/Electron.NET) for displaying the user interface.

## Motivation

Avalonia is not great, but not bad. All C# UI frameworks have their pros and cons. Although I have experienced pain points in Avalonia (for example: #797), those alone would not be sufficient justification to jump ship. I have other motivations for switching:

* AssetRipper is, and has always been, a learning experience for me. By switching to Electron.NET, I expose many new areas for personal growth.
* Web development is not niche like Avalonia. It has a massive community with numerous free resources from heavyweights like Google and Mozilla.

## Web UI Framework

Although I have not yet decided on a web UI framework to use, I am considering several options:

* [Vue.js](https://vuejs.org/)
* [Angular](https://angular.io/)
* [React](https://react.dev/)
* Pure ASP.NET

## TypeScript

I have not yet decided if I'm going to use TypeScript at all for this.

**Comment by GPU-Fried-Eggs** [comment]
I believe it's necessary to determine the technical stack as soon as possible. Mixing JavaScript and Razor MVC is not a reasonable development path. Without utilizing Blazor for C# and JavaScript interaction, we would face issues of data models being overly independent from JavaScript, and encounter problems of excessive document size during data transmission (for instance, converting a large array into a string using Convert.ToBase64String). Anticipating extensive UI development in the future could easily lead to maintainability issues. However, if the application is entirely developed on Blazor, it could result in massive build sizes and slow loading issues. Currently, I consider the following solutions to be viable:

1. Retain the current state, build a complete documentation system to support correct interaction between JavaScript files under the wwwroot directory and C# files. If additional complex animations, buttons, or multi-level pages are needed in the future, ASP is not adept at handling these, while JavaScript can manage them more efficiently and quickly. Besides, consideration should be given to incorporating reasonable model control and data exchange logic, at least solving the ability to load blobs larger than 100MB.

2. Separate the front-end and back-end, for example, using Web API (.NET) + Electron or Progressive Web Apps. This resembles our current setup of minimal data with frequent access and web API development. Since the code structure of web API routing is similar to our current code structure, the migration difficulty would not be very high.

**Comment by ds5678** [comment]
> I believe it's necessary to determine the technical stack as soon as possible.

This is likely a decision I'm not knowledgeable enough to make yet. Like I said above, part of the reason for this switch was so that I could learn more about web development.

> utilizing Blazor for C# and JavaScript interaction

I looked into this briefly when I started the rewrite, but I couldn't figure out how it would work with Electron.NET.

> excessive document size during data transmission (for instance, converting a large array into a string using Convert.ToBase64String)

I wasn't very happy using data urls for those purposes. It was mostly just to get something working until I found a better way to do it. I wanted to look into using API controllers for serving those large data blobs.

> Anticipating extensive UI development in the future

There will definitely be more, but I don't know if I would call it "extensive." I already have most of the UI functionality I want, but it's hard to say what direction things will go. I have been enjoying UI development, much more than I did with Avalonia, so it may actually be extensive as you say.

> maintainability issues

I'm not super worried about this. When something starts to become unwieldly, I look for a better way. If I lose a little time, it's okay because it wasn't really lost; it was spent learning. However, I am always, of course, open to hearing about better ways to do things.

> if the application is entirely developed on Blazor

I understand this to mean that the entirety of AssetRipper would be compiled to WebAssembly. In addition to the issues you posed, this is infeasible due to poor file system access and the 4 GB memory limit.

> Separate the front-end and back-end, for example, using Web API (.NET) + Electron

I'm not sure how this would look.
