### ISSUE TITLE
[Enhancement]: Ability to change where temp files are stored to inside the AssetRipper Folder

### ISSUE THREAD

**Issue by Demekri** [AssetRipper/AssetRipper#938]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Escape from Tarkov (standalone launcher)

### Which Unity version did this occur on?

2021.3.21f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

AssetRipper creates Temp files in C: drive when decompiling a game, so a game like Tarkov which is 45gb is impossible for me to fully decompile due to my C: drive hardly having any space to begin with. The ability to change which drive temp files are stored, for example in the AssetRipper install folder would solve this issue as I could use a different drive that has plenty of space.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12160699/AssetRipper.log)

**Comment by ds5678** [comment]
Unlikely to change

**Comment by Ileca** [comment]
I tried your software on Linux and without warning it sucked the space of /tmp (game is 5go but 8go wasn't enough), bringing / to its knees. Of course, after failing, it didn't clear all the space it had taken so I had to restart to flush /tmp.

You are basically telling us, to those who don't have much space on root or C:, that your software is unusable *on purpose*?

**Comment by ds5678** [comment]
The relevant code is here:

https://github.com/AssetRipper/AssetRipper/blob/50f0b74c0352179167edaf7a9c6ac750f0601f5f/Source/AssetRipper.IO.Files/Streams/Smart/SmartStream.cs#L29-L33

`Path.GetTempFileName()` is from the .NET SDK. It finds an unused path in the user temporary directory, which is the only recommended place to create temporary files.

You are asking for one of two things. You either want me to:

* Deviate from proper software design and create a `SmartStreamFactory` class that has to get passed around to everything.
* Do lots of work so that loading is more dynamic with only a single SmartStream open at a time. The temporary file is deleted when the stream gets closed.

**Comment by Ileca** [comment]
1/ Provide the ability to set a path to process files for people who don't have enough place in the "recommended place to create temporary files". The default will stay so you won't "deviate from proper software design".
2/ This sounds good if that takes into account the place left into the temporary directory.

I can't force you to do anything nor can I help you. It's up to you to decide if you want or not some people to not be able to use your software because of space. I don't know, I can't afford to give /tmp 50-100go for one software. I expected your software to process everything in the directory I invoked it.

**Comment by YoshiRulz** [comment]
Fixed by https://github.com/AssetRipper/AssetRipper/commit/1b4ece2b2d456dc3ab787318664df4af61039335.

Though I'm now going to ask for it to be configurable, since an exception will now be thrown if the executable is in a read-only filesystem, such as the Nix store (https://github.com/NixOS/nixpkgs/pull/427561#issuecomment-3138802642).

**Comment by ds5678** [comment]
@YoshiRulz I'm fine with you making a pull request for a `--temporary-directory` option. It would also be useful to detect if the default directory is read-only and automatically switch to `Path.GetTempPath()`.
