### ISSUE TITLE
[Bug]: Broken Mac Version

### ISSUE THREAD

**Issue by ds5678** [AssetRipper/AssetRipper#985]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

MacOS x64

### Which game did this occur on?

N/A

### Which Unity version did this occur on?

N/A

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

Users report the following error when they try to launch AssetRipper on Mac.
```
The application "AssetRipper.app" can't be opened.
```
The was directly caused by #959. If the issue can't be resolved properly, the simplest solution would be to revert that pull request.

cc: @benediktwerner

**Comment by MaxNiftyNine** [comment]
Im also having this problem

**Comment by logiota** [comment]
you can run it by using chmod +x on /AssetRipper.app/Contents/MacOS/AssetRipper 
then running it through the terminal from  /AssetRipper.app/Contents/MacOS/  
Great software!

**Comment by jdewar** [comment]
> you can run it by using chmod +x on /AssetRipper.app/Contents/MacOS/AssetRipper
> then running it through the terminal from /AssetRipper.app/Contents/MacOS/
> Great software!

I tried this on both x86 and arm64 release v0.3.3.1, but it did not work, it gives the 'This is damaged and cannot be opened.' dialog box.

**Comment by MaxNiftyNine** [comment]
> > you can run it by using chmod +x on /AssetRipper.app/Contents/MacOS/AssetRipper
> > then running it through the terminal from /AssetRipper.app/Contents/MacOS/
> > Great software!
> 
> I tried this on both x86 and arm64 release v0.3.3.1, but it did not work, it gives the 'This is damaged and cannot be opened.' dialog box.

I think what you did was just run it on assetripper.app, you need to run it on /AssetRipper.app/Contents/MacOS/AssetRipper

**Comment by MaxNiftyNine** [comment]
Its weird but you have to do this

user@MacBook-Air ~ % chmod +x /Users/user/Downloads/AssetRipper.app/Contents/MacOS/AssetRipper
user@MacBook-Air ~ %  /Users/user/Downloads/AssetRipper.app/Contents/MacOS/AssetRipper

**Comment by Javernaut** [comment]
It seems like doing `chmod +x` on AssetRipper binary doesn't solve the issue. I use macos 13.5, but exactly arm64. Could it be that `chmod` solves the issue only for x64?

**Comment by MaxNiftyNine** [comment]
> It seems like doing `chmod +x` on AssetRipper binary doesn't solve the issue. I use macos 13.5, but exactly arm64. Could it be that `chmod` solves the issue only for x64?

I use arm64, make sure you run assetripper and not assetripper.app

**Comment by jdewar** [comment]
> I think what you did was just run it on assetripper.app, you need to run it on /AssetRipper.app/Contents/MacOS/AssetRipper

Yeah, I almost made that mistake, but I read what was written carefully at one point.  I'm in the same boat as Javernaut.  I've tried with both arm64 and x86 (thinking that Rosetta would handle it)

**Comment by jdewar** [comment]
@Javernaut I followed the internet's suggestions for that error, which told me to run `xattr -cr AssetRipper.app/` to clear Mac attributes on the app/directory.  Then running the arm64 binary as you did above will work.

All of the commands in one place:
```
xattr -cr AssetRipper.app/
chmod +× AssetRipper.app/Contents/MacOS/AssetRipper
./AssetRipper.app/Contents/MacOS/AssetRipper
```

I've not used the app before, so I can't say if it work-works, but now it launches.

**Comment by josepheiba** [comment]
Yes, it worked but @jdewar, the "×" in your command is not a real "x", so anyone who copies it need to change it to the letter "x"

**Comment by benediktwerner** [comment]
@ds5678 Sorry for the delayed response. This wasn't quite caused by #959 though I guess that made the issue much worse.

Apparently, the upload-artifact action doesn't retain executable permissions (https://github.com/actions/upload-artifact/issues/38) but that would have also affected previous versions. And indeed, when I try older releases, they similarly can't be opened without first making them executable.

But I guess previously, it might have been somewhat easier to figure that out. And the flags that are added when downloading it with common browsers that cause it to show up as damaged because it isn't signed are quite annoying.

Not sure if there's a great solution to this. It looks like zipping the files before uploading would retain the executable flag. Having to extract two zips seems pretty weird but I guess it's at least self-explanatory.

Unfortunately, it doesn't avoid the "AssetRipper.app is damaged" message if one downloads the release with a browser. I don't think it can be avoided in that case without signing the app which I guess isn't going to happen.

ILSpy just has a section in the README that explains how to remove the attributes: https://github.com/icsharpcode/AvaloniaILSpy. I guess we could do the same. The alternative would ofc be to go back to just releasing a folder with random files but maybe still do the double zipping to keep the executable flags.

The nice thing about having a .app release is that it allows creating a homebrew cask so that AssetRipper can just be installed and managed via homebrew. Maybe it would be possible to just have both a .app version for homebrew or people that prefer a .app and know how to deal with it and a simple double-zipped executable as a simple alternative?

**Comment by ds5678** [comment]
> signing the app

I assume this involves paying Apple lots of money?

> Maybe it would be possible to just have both a .app version and a simple double-zipped executable

This seems inconvenient for me and confusing for users. I would need to see sufficient justification before I would agree to have two.

> nice thing about having a .app release is that it allows creating a homebrew cask so that AssetRipper can just be installed and managed via homebrew

This sounds very niche. If the "AssetRipper.app is damaged" message is unavoidable like you say, I would prefer you make a third-party utility to convert normal releases into .app releases.

> the upload-artifact action doesn't retain executable permissions

Could we include scripts with the Mac and Linux versions to make enabling these permissions easier for users?

**Comment by benediktwerner** [comment]
> I assume this involves paying Apple lots of money?

Tbh I'm not sure about that, I heard it's possible nowadays to do it for free but it probably at least requires a Mac.

> This sounds very niche.

In my experience, pretty much all developers on Macs use homebrew but I guess not sure how strongly it overlaps with AssetRipper users and how many try homebrew first for something like this.

> I would prefer you make a third-party utility to convert normal releases into .app releases.

As far as I understand, the official Homebrew repos don't really like to accept apps that don't provide .app releases. Although I guess I could at least set up an unofficial repo in that case. You're probably right that having two versions is unnecessarily confusing.

> Could we include scripts with the Mac and Linux versions to make enabling these permissions easier for users?

I guess so. Though then they still need to realize they need to run the script. Double-zipping the release seems like the most intuitive solution for users. It's just slightly odd.

**Comment by ds5678** [comment]
I'm open to double zipping

**Comment by ds5678** [comment]
I want to do a release tomorrow. Can you guys verify that everything is working on the latest alpha?
