### ISSUE TITLE
[Bug]: AudioClips with WAV data

### ISSUE THREAD

**Issue by gamecoreSRC** [AssetRipper/AssetRipper#991]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

MacOS x64

### Which game did this occur on?

Might not be applicable, but [a mod](https://gamejolt.com/games/baldshousemod/469594) that I was interested in porting to another platform.

### Which Unity version did this occur on?

To my knowledge, 2019.2.12f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Whilst trying to decompile it, it saved the audio as a completely different—unreadable by Unity—format "audioclip". The log also shows that it can't figure out what kind of audio it is

Here's an example:
Export : Audio clip data is not an FSB5 binary.
Export : Can't decode audio clip 'DaveIntroMusic' with default decoder because its audioType could not be determined.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12374147/AssetRipper.log)

(Note: pathnames were slightly altered for privacy)

**Comment by ds5678** [comment]
Even though these AudioClips have `AudioCompressionFormat.Vorbis`, their data seems to be neither Vorbis nor FSB and is actually WAV, according to the magic bytes. This is immensely suspicious, and I feel like you've wasted my time. This was likely caused by the "modder" incorrectly using other reverse engineering tools to edit the contents of the original game. I require a reproduceable test project before I do anything else with this.

**Comment by gamecoreSRC** [comment]
I have an addiction to reverse engineering mods more than games to see what said modder changed. That isn't my GameJolt if you think I'm writing this for attention. And I have no information or idea on how he decompiled the original game. I resolved the issue in the decompiled project by replacing all the audio, but nonetheless still have no idea what caused it. I'll close this and try to recreate this myself later using WAV in a built project and decompile it with AssetRipper.
